// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterPeer {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub serial: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RegisterPeerResponse {
    #[prost(bool, tag = "2")]
    pub request_pk: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PunchHoleRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "NatType", tag = "2")]
    pub nat_type: i32,
    #[prost(string, tag = "3")]
    pub licence_key: ::prost::alloc::string::String,
    #[prost(enumeration = "ConnType", tag = "4")]
    pub conn_type: i32,
    #[prost(string, tag = "5")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub version: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub udp_port: i32,
    #[prost(bool, tag = "8")]
    pub force_relay: bool,
    #[prost(int32, tag = "9")]
    pub upnp_port: i32,
    #[prost(bytes = "vec", tag = "10")]
    pub socket_addr_v6: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ControlPermissions {
    #[prost(uint64, tag = "1")]
    pub permissions: u64,
}
/// Nested message and enum types in `ControlPermissions`.
pub mod control_permissions {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Permission {
        Keyboard = 0,
        RemotePrinter = 1,
        Clipboard = 2,
        File = 3,
        Audio = 4,
        Camera = 5,
        Terminal = 6,
        Tunnel = 7,
        Restart = 8,
        Recording = 9,
        BlockInput = 10,
        RemoteModify = 11,
    }
    impl Permission {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Keyboard => "keyboard",
                Self::RemotePrinter => "remote_printer",
                Self::Clipboard => "clipboard",
                Self::File => "file",
                Self::Audio => "audio",
                Self::Camera => "camera",
                Self::Terminal => "terminal",
                Self::Tunnel => "tunnel",
                Self::Restart => "restart",
                Self::Recording => "recording",
                Self::BlockInput => "block_input",
                Self::RemoteModify => "remote_modify",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "keyboard" => Some(Self::Keyboard),
                "remote_printer" => Some(Self::RemotePrinter),
                "clipboard" => Some(Self::Clipboard),
                "file" => Some(Self::File),
                "audio" => Some(Self::Audio),
                "camera" => Some(Self::Camera),
                "terminal" => Some(Self::Terminal),
                "tunnel" => Some(Self::Tunnel),
                "restart" => Some(Self::Restart),
                "recording" => Some(Self::Recording),
                "block_input" => Some(Self::BlockInput),
                "remote_modify" => Some(Self::RemoteModify),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PunchHole {
    #[prost(bytes = "vec", tag = "1")]
    pub socket_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub relay_server: ::prost::alloc::string::String,
    #[prost(enumeration = "NatType", tag = "3")]
    pub nat_type: i32,
    #[prost(int32, tag = "4")]
    pub udp_port: i32,
    #[prost(bool, tag = "5")]
    pub force_relay: bool,
    #[prost(int32, tag = "6")]
    pub upnp_port: i32,
    #[prost(bytes = "vec", tag = "7")]
    pub socket_addr_v6: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "8")]
    pub control_permissions: ::core::option::Option<ControlPermissions>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TestNatRequest {
    #[prost(int32, tag = "1")]
    pub serial: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestNatResponse {
    #[prost(int32, tag = "1")]
    pub port: i32,
    #[prost(message, optional, tag = "2")]
    pub cu: ::core::option::Option<ConfigUpdate>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PunchHoleSent {
    #[prost(bytes = "vec", tag = "1")]
    pub socket_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub relay_server: ::prost::alloc::string::String,
    #[prost(enumeration = "NatType", tag = "4")]
    pub nat_type: i32,
    #[prost(string, tag = "5")]
    pub version: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub upnp_port: i32,
    #[prost(bytes = "vec", tag = "7")]
    pub socket_addr_v6: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterPk {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub pk: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub old_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub no_register_device: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RegisterPkResponse {
    #[prost(enumeration = "register_pk_response::Result", tag = "1")]
    pub result: i32,
    #[prost(int32, tag = "2")]
    pub keep_alive: i32,
}
/// Nested message and enum types in `RegisterPkResponse`.
pub mod register_pk_response {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Result {
        Ok = 0,
        UuidMismatch = 2,
        IdExists = 3,
        TooFrequent = 4,
        InvalidIdFormat = 5,
        NotSupport = 6,
        ServerError = 7,
    }
    impl Result {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Ok => "OK",
                Self::UuidMismatch => "UUID_MISMATCH",
                Self::IdExists => "ID_EXISTS",
                Self::TooFrequent => "TOO_FREQUENT",
                Self::InvalidIdFormat => "INVALID_ID_FORMAT",
                Self::NotSupport => "NOT_SUPPORT",
                Self::ServerError => "SERVER_ERROR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "OK" => Some(Self::Ok),
                "UUID_MISMATCH" => Some(Self::UuidMismatch),
                "ID_EXISTS" => Some(Self::IdExists),
                "TOO_FREQUENT" => Some(Self::TooFrequent),
                "INVALID_ID_FORMAT" => Some(Self::InvalidIdFormat),
                "NOT_SUPPORT" => Some(Self::NotSupport),
                "SERVER_ERROR" => Some(Self::ServerError),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PunchHoleResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub socket_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub pk: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "punch_hole_response::Failure", tag = "3")]
    pub failure: i32,
    #[prost(string, tag = "4")]
    pub relay_server: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub other_failure: ::prost::alloc::string::String,
    #[prost(int32, tag = "8")]
    pub feedback: i32,
    #[prost(bool, tag = "9")]
    pub is_udp: bool,
    #[prost(int32, tag = "10")]
    pub upnp_port: i32,
    #[prost(bytes = "vec", tag = "11")]
    pub socket_addr_v6: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "punch_hole_response::Union", tags = "5, 6")]
    pub union: ::core::option::Option<punch_hole_response::Union>,
}
/// Nested message and enum types in `PunchHoleResponse`.
pub mod punch_hole_response {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Failure {
        IdNotExist = 0,
        Offline = 2,
        LicenseMismatch = 3,
        LicenseOveruse = 4,
    }
    impl Failure {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::IdNotExist => "ID_NOT_EXIST",
                Self::Offline => "OFFLINE",
                Self::LicenseMismatch => "LICENSE_MISMATCH",
                Self::LicenseOveruse => "LICENSE_OVERUSE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ID_NOT_EXIST" => Some(Self::IdNotExist),
                "OFFLINE" => Some(Self::Offline),
                "LICENSE_MISMATCH" => Some(Self::LicenseMismatch),
                "LICENSE_OVERUSE" => Some(Self::LicenseOveruse),
                _ => None,
            }
        }
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(enumeration = "super::NatType", tag = "5")]
        NatType(i32),
        #[prost(bool, tag = "6")]
        IsLocal(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigUpdate {
    #[prost(int32, tag = "1")]
    pub serial: i32,
    #[prost(string, repeated, tag = "2")]
    pub rendezvous_servers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestRelay {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub socket_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub relay_server: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub secure: bool,
    #[prost(string, tag = "6")]
    pub licence_key: ::prost::alloc::string::String,
    #[prost(enumeration = "ConnType", tag = "7")]
    pub conn_type: i32,
    #[prost(string, tag = "8")]
    pub token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub control_permissions: ::core::option::Option<ControlPermissions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub socket_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub relay_server: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub refuse_reason: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub version: ::prost::alloc::string::String,
    #[prost(int32, tag = "9")]
    pub feedback: i32,
    #[prost(bytes = "vec", tag = "10")]
    pub socket_addr_v6: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "11")]
    pub upnp_port: i32,
    #[prost(oneof = "relay_response::Union", tags = "4, 5")]
    pub union: ::core::option::Option<relay_response::Union>,
}
/// Nested message and enum types in `RelayResponse`.
pub mod relay_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(string, tag = "4")]
        Id(::prost::alloc::string::String),
        #[prost(bytes, tag = "5")]
        Pk(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SoftwareUpdate {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchLocalAddr {
    #[prost(bytes = "vec", tag = "1")]
    pub socket_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub relay_server: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub socket_addr_v6: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub control_permissions: ::core::option::Option<ControlPermissions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalAddr {
    #[prost(bytes = "vec", tag = "1")]
    pub socket_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub local_addr: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub relay_server: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub version: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub socket_addr_v6: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerDiscovery {
    #[prost(string, tag = "1")]
    pub cmd: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub mac: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub platform: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub misc: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnlineRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub peers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnlineResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub states: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyExchange {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheck {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RendezvousMessage {
    #[prost(
        oneof = "rendezvous_message::Union",
        tags = "6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26"
    )]
    pub union: ::core::option::Option<rendezvous_message::Union>,
}
/// Nested message and enum types in `RendezvousMessage`.
pub mod rendezvous_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "6")]
        RegisterPeer(super::RegisterPeer),
        #[prost(message, tag = "7")]
        RegisterPeerResponse(super::RegisterPeerResponse),
        #[prost(message, tag = "8")]
        PunchHoleRequest(super::PunchHoleRequest),
        #[prost(message, tag = "9")]
        PunchHole(super::PunchHole),
        #[prost(message, tag = "10")]
        PunchHoleSent(super::PunchHoleSent),
        #[prost(message, tag = "11")]
        PunchHoleResponse(super::PunchHoleResponse),
        #[prost(message, tag = "12")]
        FetchLocalAddr(super::FetchLocalAddr),
        #[prost(message, tag = "13")]
        LocalAddr(super::LocalAddr),
        #[prost(message, tag = "14")]
        ConfigureUpdate(super::ConfigUpdate),
        #[prost(message, tag = "15")]
        RegisterPk(super::RegisterPk),
        #[prost(message, tag = "16")]
        RegisterPkResponse(super::RegisterPkResponse),
        #[prost(message, tag = "17")]
        SoftwareUpdate(super::SoftwareUpdate),
        #[prost(message, tag = "18")]
        RequestRelay(super::RequestRelay),
        #[prost(message, tag = "19")]
        RelayResponse(super::RelayResponse),
        #[prost(message, tag = "20")]
        TestNatRequest(super::TestNatRequest),
        #[prost(message, tag = "21")]
        TestNatResponse(super::TestNatResponse),
        #[prost(message, tag = "22")]
        PeerDiscovery(super::PeerDiscovery),
        #[prost(message, tag = "23")]
        OnlineRequest(super::OnlineRequest),
        #[prost(message, tag = "24")]
        OnlineResponse(super::OnlineResponse),
        #[prost(message, tag = "25")]
        KeyExchange(super::KeyExchange),
        #[prost(message, tag = "26")]
        Hc(super::HealthCheck),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConnType {
    DefaultConn = 0,
    FileTransfer = 1,
    PortForward = 2,
    Rdp = 3,
    ViewCamera = 4,
    Terminal = 5,
}
impl ConnType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DefaultConn => "DEFAULT_CONN",
            Self::FileTransfer => "FILE_TRANSFER",
            Self::PortForward => "PORT_FORWARD",
            Self::Rdp => "RDP",
            Self::ViewCamera => "VIEW_CAMERA",
            Self::Terminal => "TERMINAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEFAULT_CONN" => Some(Self::DefaultConn),
            "FILE_TRANSFER" => Some(Self::FileTransfer),
            "PORT_FORWARD" => Some(Self::PortForward),
            "RDP" => Some(Self::Rdp),
            "VIEW_CAMERA" => Some(Self::ViewCamera),
            "TERMINAL" => Some(Self::Terminal),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NatType {
    UnknownNat = 0,
    Asymmetric = 1,
    Symmetric = 2,
}
impl NatType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownNat => "UNKNOWN_NAT",
            Self::Asymmetric => "ASYMMETRIC",
            Self::Symmetric => "SYMMETRIC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_NAT" => Some(Self::UnknownNat),
            "ASYMMETRIC" => Some(Self::Asymmetric),
            "SYMMETRIC" => Some(Self::Symmetric),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncodedVideoFrame {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "2")]
    pub key: bool,
    #[prost(int64, tag = "3")]
    pub pts: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncodedVideoFrames {
    #[prost(message, repeated, tag = "1")]
    pub frames: ::prost::alloc::vec::Vec<EncodedVideoFrame>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Rgb {
    #[prost(bool, tag = "1")]
    pub compress: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Yuv {
    #[prost(bool, tag = "1")]
    pub compress: bool,
    #[prost(int32, tag = "2")]
    pub stride: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VideoFrame {
    #[prost(int32, tag = "14")]
    pub display: i32,
    #[prost(oneof = "video_frame::Union", tags = "6, 7, 8, 10, 11, 12, 13")]
    pub union: ::core::option::Option<video_frame::Union>,
}
/// Nested message and enum types in `VideoFrame`.
pub mod video_frame {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "6")]
        Vp9s(super::EncodedVideoFrames),
        #[prost(message, tag = "7")]
        Rgb(super::Rgb),
        #[prost(message, tag = "8")]
        Yuv(super::Yuv),
        #[prost(message, tag = "10")]
        H264s(super::EncodedVideoFrames),
        #[prost(message, tag = "11")]
        H265s(super::EncodedVideoFrames),
        #[prost(message, tag = "12")]
        Vp8s(super::EncodedVideoFrames),
        #[prost(message, tag = "13")]
        Av1s(super::EncodedVideoFrames),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IdPk {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub pk: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisplayInfo {
    #[prost(sint32, tag = "1")]
    pub x: i32,
    #[prost(sint32, tag = "2")]
    pub y: i32,
    #[prost(int32, tag = "3")]
    pub width: i32,
    #[prost(int32, tag = "4")]
    pub height: i32,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub online: bool,
    #[prost(bool, tag = "7")]
    pub cursor_embedded: bool,
    #[prost(message, optional, tag = "8")]
    pub original_resolution: ::core::option::Option<Resolution>,
    #[prost(double, tag = "9")]
    pub scale: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PortForward {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub port: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTransfer {
    #[prost(string, tag = "1")]
    pub dir: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub show_hidden: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ViewCamera {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OsLogin {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub password: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub my_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub my_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub option: ::core::option::Option<OptionMessage>,
    #[prost(bool, tag = "9")]
    pub video_ack_required: bool,
    #[prost(uint64, tag = "10")]
    pub session_id: u64,
    #[prost(string, tag = "11")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "12")]
    pub os_login: ::core::option::Option<OsLogin>,
    #[prost(string, tag = "13")]
    pub my_platform: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "14")]
    pub hwid: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "login_request::Union", tags = "7, 8, 15, 16")]
    pub union: ::core::option::Option<login_request::Union>,
}
/// Nested message and enum types in `LoginRequest`.
pub mod login_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "7")]
        FileTransfer(super::FileTransfer),
        #[prost(message, tag = "8")]
        PortForward(super::PortForward),
        #[prost(message, tag = "15")]
        ViewCamera(super::ViewCamera),
        #[prost(message, tag = "16")]
        Terminal(super::Terminal),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Terminal {
    #[prost(string, tag = "1")]
    pub service_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Auth2Fa {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub hwid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatMessage {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Features {
    #[prost(bool, tag = "1")]
    pub privacy_mode: bool,
    #[prost(bool, tag = "2")]
    pub terminal: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CodecAbility {
    #[prost(bool, tag = "1")]
    pub vp8: bool,
    #[prost(bool, tag = "2")]
    pub vp9: bool,
    #[prost(bool, tag = "3")]
    pub av1: bool,
    #[prost(bool, tag = "4")]
    pub h264: bool,
    #[prost(bool, tag = "5")]
    pub h265: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SupportedEncoding {
    #[prost(bool, tag = "1")]
    pub h264: bool,
    #[prost(bool, tag = "2")]
    pub h265: bool,
    #[prost(bool, tag = "3")]
    pub vp8: bool,
    #[prost(bool, tag = "4")]
    pub av1: bool,
    #[prost(message, optional, tag = "5")]
    pub i444: ::core::option::Option<CodecAbility>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeerInfo {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub platform: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub displays: ::prost::alloc::vec::Vec<DisplayInfo>,
    #[prost(int32, tag = "5")]
    pub current_display: i32,
    #[prost(bool, tag = "6")]
    pub sas_enabled: bool,
    #[prost(string, tag = "7")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub features: ::core::option::Option<Features>,
    #[prost(message, optional, tag = "10")]
    pub encoding: ::core::option::Option<SupportedEncoding>,
    #[prost(message, optional, tag = "11")]
    pub resolutions: ::core::option::Option<SupportedResolutions>,
    #[prost(string, tag = "12")]
    pub platform_additions: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "13")]
    pub windows_sessions: ::core::option::Option<WindowsSessions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WindowsSession {
    #[prost(uint32, tag = "1")]
    pub sid: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    #[prost(bool, tag = "3")]
    pub enable_trusted_devices: bool,
    #[prost(oneof = "login_response::Union", tags = "1, 2")]
    pub union: ::core::option::Option<login_response::Union>,
}
/// Nested message and enum types in `LoginResponse`.
pub mod login_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(string, tag = "1")]
        Error(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        PeerInfo(super::PeerInfo),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TouchScaleUpdate {
    #[prost(int32, tag = "1")]
    pub scale: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TouchPanStart {
    #[prost(int32, tag = "1")]
    pub x: i32,
    #[prost(int32, tag = "2")]
    pub y: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TouchPanUpdate {
    #[prost(int32, tag = "1")]
    pub x: i32,
    #[prost(int32, tag = "2")]
    pub y: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TouchPanEnd {
    #[prost(int32, tag = "1")]
    pub x: i32,
    #[prost(int32, tag = "2")]
    pub y: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TouchEvent {
    #[prost(oneof = "touch_event::Union", tags = "1, 2, 3, 4")]
    pub union: ::core::option::Option<touch_event::Union>,
}
/// Nested message and enum types in `TouchEvent`.
pub mod touch_event {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "1")]
        ScaleUpdate(super::TouchScaleUpdate),
        #[prost(message, tag = "2")]
        PanStart(super::TouchPanStart),
        #[prost(message, tag = "3")]
        PanUpdate(super::TouchPanUpdate),
        #[prost(message, tag = "4")]
        PanEnd(super::TouchPanEnd),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PointerDeviceEvent {
    #[prost(enumeration = "ControlKey", repeated, tag = "2")]
    pub modifiers: ::prost::alloc::vec::Vec<i32>,
    #[prost(oneof = "pointer_device_event::Union", tags = "1")]
    pub union: ::core::option::Option<pointer_device_event::Union>,
}
/// Nested message and enum types in `PointerDeviceEvent`.
pub mod pointer_device_event {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "1")]
        TouchEvent(super::TouchEvent),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MouseEvent {
    #[prost(int32, tag = "1")]
    pub mask: i32,
    #[prost(sint32, tag = "2")]
    pub x: i32,
    #[prost(sint32, tag = "3")]
    pub y: i32,
    #[prost(enumeration = "ControlKey", repeated, tag = "4")]
    pub modifiers: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyEvent {
    #[prost(bool, tag = "1")]
    pub down: bool,
    #[prost(bool, tag = "2")]
    pub press: bool,
    #[prost(enumeration = "ControlKey", repeated, tag = "8")]
    pub modifiers: ::prost::alloc::vec::Vec<i32>,
    #[prost(enumeration = "KeyboardMode", tag = "9")]
    pub mode: i32,
    #[prost(oneof = "key_event::Union", tags = "3, 4, 5, 6, 7")]
    pub union: ::core::option::Option<key_event::Union>,
}
/// Nested message and enum types in `KeyEvent`.
pub mod key_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(enumeration = "super::ControlKey", tag = "3")]
        ControlKey(i32),
        #[prost(uint32, tag = "4")]
        Chr(u32),
        #[prost(uint32, tag = "5")]
        Unicode(u32),
        #[prost(string, tag = "6")]
        Seq(::prost::alloc::string::String),
        #[prost(uint32, tag = "7")]
        Win2winHotkey(u32),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CursorData {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(sint32, tag = "2")]
    pub hotx: i32,
    #[prost(sint32, tag = "3")]
    pub hoty: i32,
    #[prost(int32, tag = "4")]
    pub width: i32,
    #[prost(int32, tag = "5")]
    pub height: i32,
    #[prost(bytes = "vec", tag = "6")]
    pub colors: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CursorPosition {
    #[prost(sint32, tag = "1")]
    pub x: i32,
    #[prost(sint32, tag = "2")]
    pub y: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hash {
    #[prost(string, tag = "1")]
    pub salt: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub challenge: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Clipboard {
    #[prost(bool, tag = "1")]
    pub compress: bool,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub width: i32,
    #[prost(int32, tag = "4")]
    pub height: i32,
    #[prost(enumeration = "ClipboardFormat", tag = "5")]
    pub format: i32,
    #[prost(string, tag = "6")]
    pub special_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MultiClipboards {
    #[prost(message, repeated, tag = "1")]
    pub clipboards: ::prost::alloc::vec::Vec<Clipboard>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileEntry {
    #[prost(enumeration = "FileType", tag = "1")]
    pub entry_type: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_hidden: bool,
    #[prost(uint64, tag = "4")]
    pub size: u64,
    #[prost(uint64, tag = "5")]
    pub modified_time: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileDirectory {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub entries: ::prost::alloc::vec::Vec<FileEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadDir {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub include_hidden: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadAllFiles {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub include_hidden: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileRename {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileAction {
    #[prost(oneof = "file_action::Union", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10")]
    pub union: ::core::option::Option<file_action::Union>,
}
/// Nested message and enum types in `FileAction`.
pub mod file_action {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "1")]
        ReadDir(super::ReadDir),
        #[prost(message, tag = "2")]
        Send(super::FileTransferSendRequest),
        #[prost(message, tag = "3")]
        Receive(super::FileTransferReceiveRequest),
        #[prost(message, tag = "4")]
        Create(super::FileDirCreate),
        #[prost(message, tag = "5")]
        RemoveDir(super::FileRemoveDir),
        #[prost(message, tag = "6")]
        RemoveFile(super::FileRemoveFile),
        #[prost(message, tag = "7")]
        AllFiles(super::ReadAllFiles),
        #[prost(message, tag = "8")]
        Cancel(super::FileTransferCancel),
        #[prost(message, tag = "9")]
        SendConfirm(super::FileTransferSendConfirmRequest),
        #[prost(message, tag = "10")]
        Rename(super::FileRename),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileTransferCancel {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileResponse {
    #[prost(oneof = "file_response::Union", tags = "1, 2, 3, 4, 5")]
    pub union: ::core::option::Option<file_response::Union>,
}
/// Nested message and enum types in `FileResponse`.
pub mod file_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "1")]
        Dir(super::FileDirectory),
        #[prost(message, tag = "2")]
        Block(super::FileTransferBlock),
        #[prost(message, tag = "3")]
        Error(super::FileTransferError),
        #[prost(message, tag = "4")]
        Done(super::FileTransferDone),
        #[prost(message, tag = "5")]
        Digest(super::FileTransferDigest),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileTransferDigest {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(sint32, tag = "2")]
    pub file_num: i32,
    #[prost(uint64, tag = "3")]
    pub last_modified: u64,
    #[prost(uint64, tag = "4")]
    pub file_size: u64,
    #[prost(bool, tag = "5")]
    pub is_upload: bool,
    #[prost(bool, tag = "6")]
    pub is_identical: bool,
    #[prost(uint64, tag = "7")]
    pub transferred_size: u64,
    #[prost(bool, tag = "8")]
    pub is_resume: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTransferBlock {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(sint32, tag = "2")]
    pub file_num: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "4")]
    pub compressed: bool,
    #[prost(uint32, tag = "5")]
    pub blk_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTransferError {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    #[prost(sint32, tag = "3")]
    pub file_num: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTransferSendRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub include_hidden: bool,
    #[prost(int32, tag = "4")]
    pub file_num: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileTransferSendConfirmRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(sint32, tag = "2")]
    pub file_num: i32,
    #[prost(oneof = "file_transfer_send_confirm_request::Union", tags = "3, 4")]
    pub union: ::core::option::Option<file_transfer_send_confirm_request::Union>,
}
/// Nested message and enum types in `FileTransferSendConfirmRequest`.
pub mod file_transfer_send_confirm_request {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(bool, tag = "3")]
        Skip(bool),
        #[prost(uint32, tag = "4")]
        OffsetBlk(u32),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FileTransferDone {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(sint32, tag = "2")]
    pub file_num: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileTransferReceiveRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub files: ::prost::alloc::vec::Vec<FileEntry>,
    #[prost(int32, tag = "4")]
    pub file_num: i32,
    #[prost(uint64, tag = "5")]
    pub total_size: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileRemoveDir {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub recursive: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileRemoveFile {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(sint32, tag = "3")]
    pub file_num: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileDirCreate {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Resolution {
    #[prost(int32, tag = "1")]
    pub width: i32,
    #[prost(int32, tag = "2")]
    pub height: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DisplayResolution {
    #[prost(int32, tag = "1")]
    pub display: i32,
    #[prost(message, optional, tag = "2")]
    pub resolution: ::core::option::Option<Resolution>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SupportedResolutions {
    #[prost(message, repeated, tag = "1")]
    pub resolutions: ::prost::alloc::vec::Vec<Resolution>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwitchDisplay {
    #[prost(int32, tag = "1")]
    pub display: i32,
    #[prost(sint32, tag = "2")]
    pub x: i32,
    #[prost(sint32, tag = "3")]
    pub y: i32,
    #[prost(int32, tag = "4")]
    pub width: i32,
    #[prost(int32, tag = "5")]
    pub height: i32,
    #[prost(bool, tag = "6")]
    pub cursor_embedded: bool,
    #[prost(message, optional, tag = "7")]
    pub resolutions: ::core::option::Option<SupportedResolutions>,
    #[prost(message, optional, tag = "8")]
    pub original_resolution: ::core::option::Option<Resolution>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaptureDisplays {
    #[prost(int32, repeated, tag = "1")]
    pub add: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "2")]
    pub sub: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "3")]
    pub set: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ToggleVirtualDisplay {
    #[prost(int32, tag = "1")]
    pub display: i32,
    #[prost(bool, tag = "2")]
    pub on: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TogglePrivacyMode {
    #[prost(string, tag = "1")]
    pub impl_key: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub on: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PermissionInfo {
    #[prost(enumeration = "permission_info::Permission", tag = "1")]
    pub permission: i32,
    #[prost(bool, tag = "2")]
    pub enabled: bool,
}
/// Nested message and enum types in `PermissionInfo`.
pub mod permission_info {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Permission {
        Keyboard = 0,
        Clipboard = 2,
        Audio = 3,
        File = 4,
        Restart = 5,
        Recording = 6,
        BlockInput = 7,
    }
    impl Permission {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Keyboard => "Keyboard",
                Self::Clipboard => "Clipboard",
                Self::Audio => "Audio",
                Self::File => "File",
                Self::Restart => "Restart",
                Self::Recording => "Recording",
                Self::BlockInput => "BlockInput",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Keyboard" => Some(Self::Keyboard),
                "Clipboard" => Some(Self::Clipboard),
                "Audio" => Some(Self::Audio),
                "File" => Some(Self::File),
                "Restart" => Some(Self::Restart),
                "Recording" => Some(Self::Recording),
                "BlockInput" => Some(Self::BlockInput),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SupportedDecoding {
    #[prost(int32, tag = "1")]
    pub ability_vp9: i32,
    #[prost(int32, tag = "2")]
    pub ability_h264: i32,
    #[prost(int32, tag = "3")]
    pub ability_h265: i32,
    #[prost(enumeration = "supported_decoding::PreferCodec", tag = "4")]
    pub prefer: i32,
    #[prost(int32, tag = "5")]
    pub ability_vp8: i32,
    #[prost(int32, tag = "6")]
    pub ability_av1: i32,
    #[prost(message, optional, tag = "7")]
    pub i444: ::core::option::Option<CodecAbility>,
    #[prost(enumeration = "Chroma", tag = "8")]
    pub prefer_chroma: i32,
}
/// Nested message and enum types in `SupportedDecoding`.
pub mod supported_decoding {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PreferCodec {
        Auto = 0,
        Vp9 = 1,
        H264 = 2,
        H265 = 3,
        Vp8 = 4,
        Av1 = 5,
    }
    impl PreferCodec {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Auto => "Auto",
                Self::Vp9 => "VP9",
                Self::H264 => "H264",
                Self::H265 => "H265",
                Self::Vp8 => "VP8",
                Self::Av1 => "AV1",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "Auto" => Some(Self::Auto),
                "VP9" => Some(Self::Vp9),
                "H264" => Some(Self::H264),
                "H265" => Some(Self::H265),
                "VP8" => Some(Self::Vp8),
                "AV1" => Some(Self::Av1),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OptionMessage {
    #[prost(enumeration = "ImageQuality", tag = "1")]
    pub image_quality: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "2")]
    pub lock_after_session_end: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "3")]
    pub show_remote_cursor: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "4")]
    pub privacy_mode: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "5")]
    pub block_input: i32,
    #[prost(int32, tag = "6")]
    pub custom_image_quality: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "7")]
    pub disable_audio: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "8")]
    pub disable_clipboard: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "9")]
    pub enable_file_transfer: i32,
    #[prost(message, optional, tag = "10")]
    pub supported_decoding: ::core::option::Option<SupportedDecoding>,
    #[prost(int32, tag = "11")]
    pub custom_fps: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "12")]
    pub disable_keyboard: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "15")]
    pub follow_remote_cursor: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "16")]
    pub follow_remote_window: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "17")]
    pub disable_camera: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "18")]
    pub terminal_persistent: i32,
    #[prost(enumeration = "option_message::BoolOption", tag = "19")]
    pub show_my_cursor: i32,
}
/// Nested message and enum types in `OptionMessage`.
pub mod option_message {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum BoolOption {
        NotSet = 0,
        No = 1,
        Yes = 2,
    }
    impl BoolOption {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::NotSet => "NotSet",
                Self::No => "No",
                Self::Yes => "Yes",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NotSet" => Some(Self::NotSet),
                "No" => Some(Self::No),
                "Yes" => Some(Self::Yes),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TestDelay {
    #[prost(int64, tag = "1")]
    pub time: i64,
    #[prost(bool, tag = "2")]
    pub from_client: bool,
    #[prost(uint32, tag = "3")]
    pub last_delay: u32,
    #[prost(uint32, tag = "4")]
    pub target_bitrate: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublicKey {
    #[prost(bytes = "vec", tag = "1")]
    pub asymmetric_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub symmetric_value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignedId {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AudioFormat {
    #[prost(uint32, tag = "1")]
    pub sample_rate: u32,
    #[prost(uint32, tag = "2")]
    pub channels: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AudioFrame {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageBox {
    #[prost(string, tag = "1")]
    pub msgtype: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub link: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackNotification {
    #[prost(string, tag = "3")]
    pub details: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub impl_key: ::prost::alloc::string::String,
    #[prost(oneof = "back_notification::Union", tags = "1, 2")]
    pub union: ::core::option::Option<back_notification::Union>,
}
/// Nested message and enum types in `BackNotification`.
pub mod back_notification {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum BlockInputState {
        BlkStateUnknown = 0,
        BlkOnSucceeded = 2,
        BlkOnFailed = 3,
        BlkOffSucceeded = 4,
        BlkOffFailed = 5,
    }
    impl BlockInputState {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::BlkStateUnknown => "BlkStateUnknown",
                Self::BlkOnSucceeded => "BlkOnSucceeded",
                Self::BlkOnFailed => "BlkOnFailed",
                Self::BlkOffSucceeded => "BlkOffSucceeded",
                Self::BlkOffFailed => "BlkOffFailed",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "BlkStateUnknown" => Some(Self::BlkStateUnknown),
                "BlkOnSucceeded" => Some(Self::BlkOnSucceeded),
                "BlkOnFailed" => Some(Self::BlkOnFailed),
                "BlkOffSucceeded" => Some(Self::BlkOffSucceeded),
                "BlkOffFailed" => Some(Self::BlkOffFailed),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PrivacyModeState {
        PrvStateUnknown = 0,
        PrvOnByOther = 2,
        PrvNotSupported = 3,
        PrvOnSucceeded = 4,
        PrvOnFailedDenied = 5,
        PrvOnFailedPlugin = 6,
        PrvOnFailed = 7,
        PrvOffSucceeded = 8,
        PrvOffByPeer = 9,
        PrvOffFailed = 10,
        PrvOffUnknown = 11,
    }
    impl PrivacyModeState {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::PrvStateUnknown => "PrvStateUnknown",
                Self::PrvOnByOther => "PrvOnByOther",
                Self::PrvNotSupported => "PrvNotSupported",
                Self::PrvOnSucceeded => "PrvOnSucceeded",
                Self::PrvOnFailedDenied => "PrvOnFailedDenied",
                Self::PrvOnFailedPlugin => "PrvOnFailedPlugin",
                Self::PrvOnFailed => "PrvOnFailed",
                Self::PrvOffSucceeded => "PrvOffSucceeded",
                Self::PrvOffByPeer => "PrvOffByPeer",
                Self::PrvOffFailed => "PrvOffFailed",
                Self::PrvOffUnknown => "PrvOffUnknown",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PrvStateUnknown" => Some(Self::PrvStateUnknown),
                "PrvOnByOther" => Some(Self::PrvOnByOther),
                "PrvNotSupported" => Some(Self::PrvNotSupported),
                "PrvOnSucceeded" => Some(Self::PrvOnSucceeded),
                "PrvOnFailedDenied" => Some(Self::PrvOnFailedDenied),
                "PrvOnFailedPlugin" => Some(Self::PrvOnFailedPlugin),
                "PrvOnFailed" => Some(Self::PrvOnFailed),
                "PrvOffSucceeded" => Some(Self::PrvOffSucceeded),
                "PrvOffByPeer" => Some(Self::PrvOffByPeer),
                "PrvOffFailed" => Some(Self::PrvOffFailed),
                "PrvOffUnknown" => Some(Self::PrvOffUnknown),
                _ => None,
            }
        }
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(enumeration = "PrivacyModeState", tag = "1")]
        PrivacyModeState(i32),
        #[prost(enumeration = "BlockInputState", tag = "2")]
        BlockInputState(i32),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElevationRequestWithLogon {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElevationRequest {
    #[prost(oneof = "elevation_request::Union", tags = "1, 2")]
    pub union: ::core::option::Option<elevation_request::Union>,
}
/// Nested message and enum types in `ElevationRequest`.
pub mod elevation_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(bool, tag = "1")]
        Direct(bool),
        #[prost(message, tag = "2")]
        Logon(super::ElevationRequestWithLogon),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwitchSidesRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub uuid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwitchSidesResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub lr: ::core::option::Option<LoginRequest>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SwitchBack {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WindowsSessions {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<WindowsSession>,
    #[prost(uint32, tag = "2")]
    pub current_sid: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MessageQuery {
    #[prost(int32, tag = "1")]
    pub switch_display: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VoiceCallRequest {
    #[prost(int64, tag = "1")]
    pub req_timestamp: i64,
    #[prost(bool, tag = "2")]
    pub is_connect: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VoiceCallResponse {
    #[prost(bool, tag = "1")]
    pub accepted: bool,
    #[prost(int64, tag = "2")]
    pub req_timestamp: i64,
    #[prost(int64, tag = "3")]
    pub ack_timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenshotRequest {
    #[prost(int32, tag = "1")]
    pub display: i32,
    #[prost(string, tag = "2")]
    pub sid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenshotResponse {
    #[prost(string, tag = "1")]
    pub sid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub msg: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Misc {
    #[prost(
        oneof = "misc::Union",
        tags = "4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38"
    )]
    pub union: ::core::option::Option<misc::Union>,
}
/// Nested message and enum types in `Misc`.
pub mod misc {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "4")]
        ChatMessage(super::ChatMessage),
        #[prost(message, tag = "5")]
        SwitchDisplay(super::SwitchDisplay),
        #[prost(message, tag = "6")]
        PermissionInfo(super::PermissionInfo),
        #[prost(message, tag = "7")]
        Option(super::OptionMessage),
        #[prost(message, tag = "8")]
        AudioFormat(super::AudioFormat),
        #[prost(string, tag = "9")]
        CloseReason(::prost::alloc::string::String),
        #[prost(bool, tag = "10")]
        RefreshVideo(bool),
        #[prost(bool, tag = "12")]
        VideoReceived(bool),
        #[prost(message, tag = "13")]
        BackNotification(super::BackNotification),
        #[prost(bool, tag = "14")]
        RestartRemoteDevice(bool),
        #[prost(bool, tag = "15")]
        Uac(bool),
        #[prost(bool, tag = "16")]
        ForegroundWindowElevated(bool),
        #[prost(bool, tag = "17")]
        StopService(bool),
        #[prost(message, tag = "18")]
        ElevationRequest(super::ElevationRequest),
        #[prost(string, tag = "19")]
        ElevationResponse(::prost::alloc::string::String),
        #[prost(bool, tag = "20")]
        PortableServiceRunning(bool),
        #[prost(message, tag = "21")]
        SwitchSidesRequest(super::SwitchSidesRequest),
        #[prost(message, tag = "22")]
        SwitchBack(super::SwitchBack),
        #[prost(message, tag = "24")]
        ChangeResolution(super::Resolution),
        #[prost(uint32, tag = "27")]
        FullSpeedFps(u32),
        #[prost(uint32, tag = "28")]
        AutoAdjustFps(u32),
        #[prost(bool, tag = "29")]
        ClientRecordStatus(bool),
        #[prost(message, tag = "30")]
        CaptureDisplays(super::CaptureDisplays),
        #[prost(int32, tag = "31")]
        RefreshVideoDisplay(i32),
        #[prost(message, tag = "32")]
        ToggleVirtualDisplay(super::ToggleVirtualDisplay),
        #[prost(message, tag = "33")]
        TogglePrivacyMode(super::TogglePrivacyMode),
        #[prost(message, tag = "34")]
        SupportedEncoding(super::SupportedEncoding),
        #[prost(uint32, tag = "35")]
        SelectedSid(u32),
        #[prost(message, tag = "36")]
        ChangeDisplayResolution(super::DisplayResolution),
        #[prost(message, tag = "37")]
        MessageQuery(super::MessageQuery),
        #[prost(int32, tag = "38")]
        FollowCurrentDisplay(i32),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(
        oneof = "message::Union",
        tags = "3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30"
    )]
    pub union: ::core::option::Option<message::Union>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "3")]
        SignedId(super::SignedId),
        #[prost(message, tag = "4")]
        PublicKey(super::PublicKey),
        #[prost(message, tag = "5")]
        TestDelay(super::TestDelay),
        #[prost(message, tag = "6")]
        VideoFrame(super::VideoFrame),
        #[prost(message, tag = "7")]
        LoginRequest(super::LoginRequest),
        #[prost(message, tag = "8")]
        LoginResponse(super::LoginResponse),
        #[prost(message, tag = "9")]
        Hash(super::Hash),
        #[prost(message, tag = "10")]
        MouseEvent(super::MouseEvent),
        #[prost(message, tag = "11")]
        AudioFrame(super::AudioFrame),
        #[prost(message, tag = "12")]
        CursorData(super::CursorData),
        #[prost(message, tag = "13")]
        CursorPosition(super::CursorPosition),
        #[prost(uint64, tag = "14")]
        CursorId(u64),
        #[prost(message, tag = "15")]
        KeyEvent(super::KeyEvent),
        #[prost(message, tag = "16")]
        Clipboard(super::Clipboard),
        #[prost(message, tag = "17")]
        FileAction(super::FileAction),
        #[prost(message, tag = "18")]
        FileResponse(super::FileResponse),
        #[prost(message, tag = "19")]
        Misc(super::Misc),
        #[prost(message, tag = "20")]
        Cliprdr(super::Cliprdr),
        #[prost(message, tag = "21")]
        MessageBox(super::MessageBox),
        #[prost(message, tag = "22")]
        SwitchSidesResponse(super::SwitchSidesResponse),
        #[prost(message, tag = "23")]
        VoiceCallRequest(super::VoiceCallRequest),
        #[prost(message, tag = "24")]
        VoiceCallResponse(super::VoiceCallResponse),
        #[prost(message, tag = "25")]
        PeerInfo(super::PeerInfo),
        #[prost(message, tag = "26")]
        PointerDeviceEvent(super::PointerDeviceEvent),
        #[prost(message, tag = "27")]
        Auth2fa(super::Auth2Fa),
        #[prost(message, tag = "28")]
        MultiClipboards(super::MultiClipboards),
        #[prost(message, tag = "29")]
        ScreenshotRequest(super::ScreenshotRequest),
        #[prost(message, tag = "30")]
        ScreenshotResponse(super::ScreenshotResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cliprdr {
    #[prost(oneof = "cliprdr::Union", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub union: ::core::option::Option<cliprdr::Union>,
}
/// Nested message and enum types in `Cliprdr`.
pub mod cliprdr {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Union {
        #[prost(message, tag = "1")]
        Ready(super::CliprdrMonitorReady),
        #[prost(message, tag = "2")]
        FormatList(super::CliprdrServerFormatList),
        #[prost(message, tag = "3")]
        FormatListResponse(super::CliprdrServerFormatListResponse),
        #[prost(message, tag = "4")]
        FormatDataRequest(super::CliprdrServerFormatDataRequest),
        #[prost(message, tag = "5")]
        FormatDataResponse(super::CliprdrServerFormatDataResponse),
        #[prost(message, tag = "6")]
        FileContentsRequest(super::CliprdrFileContentsRequest),
        #[prost(message, tag = "7")]
        FileContentsResponse(super::CliprdrFileContentsResponse),
        #[prost(message, tag = "8")]
        TryEmpty(super::CliprdrTryEmpty),
        #[prost(message, tag = "9")]
        Files(super::CliprdrFiles),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CliprdrMonitorReady {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CliprdrFormat {
    #[prost(int32, tag = "2")]
    pub id: i32,
    #[prost(string, tag = "3")]
    pub format: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CliprdrServerFormatList {
    #[prost(message, repeated, tag = "2")]
    pub formats: ::prost::alloc::vec::Vec<CliprdrFormat>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CliprdrServerFormatListResponse {
    #[prost(int32, tag = "2")]
    pub msg_flags: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CliprdrServerFormatDataRequest {
    #[prost(int32, tag = "2")]
    pub requested_format_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CliprdrServerFormatDataResponse {
    #[prost(int32, tag = "2")]
    pub msg_flags: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub format_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CliprdrFileContentsRequest {
    #[prost(int32, tag = "2")]
    pub stream_id: i32,
    #[prost(int32, tag = "3")]
    pub list_index: i32,
    #[prost(int32, tag = "4")]
    pub dw_flags: i32,
    #[prost(int32, tag = "5")]
    pub n_position_low: i32,
    #[prost(int32, tag = "6")]
    pub n_position_high: i32,
    #[prost(int32, tag = "7")]
    pub cb_requested: i32,
    #[prost(bool, tag = "8")]
    pub have_clip_data_id: bool,
    #[prost(int32, tag = "9")]
    pub clip_data_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CliprdrFileContentsResponse {
    #[prost(int32, tag = "3")]
    pub msg_flags: i32,
    #[prost(int32, tag = "4")]
    pub stream_id: i32,
    #[prost(bytes = "vec", tag = "5")]
    pub requested_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CliprdrTryEmpty {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CliprdrFile {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub size: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CliprdrFiles {
    #[prost(message, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<CliprdrFile>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Chroma {
    I420 = 0,
    I444 = 1,
}
impl Chroma {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::I420 => "I420",
            Self::I444 => "I444",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "I420" => Some(Self::I420),
            "I444" => Some(Self::I444),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum KeyboardMode {
    Legacy = 0,
    Map = 1,
    Translate = 2,
    Auto = 3,
}
impl KeyboardMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Legacy => "Legacy",
            Self::Map => "Map",
            Self::Translate => "Translate",
            Self::Auto => "Auto",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Legacy" => Some(Self::Legacy),
            "Map" => Some(Self::Map),
            "Translate" => Some(Self::Translate),
            "Auto" => Some(Self::Auto),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ControlKey {
    Unknown = 0,
    Alt = 1,
    Backspace = 2,
    CapsLock = 3,
    Control = 4,
    Delete = 5,
    DownArrow = 6,
    End = 7,
    Escape = 8,
    F1 = 9,
    F10 = 10,
    F11 = 11,
    F12 = 12,
    F2 = 13,
    F3 = 14,
    F4 = 15,
    F5 = 16,
    F6 = 17,
    F7 = 18,
    F8 = 19,
    F9 = 20,
    Home = 21,
    LeftArrow = 22,
    Meta = 23,
    Option = 24,
    PageDown = 25,
    PageUp = 26,
    Return = 27,
    RightArrow = 28,
    Shift = 29,
    Space = 30,
    Tab = 31,
    UpArrow = 32,
    Numpad0 = 33,
    Numpad1 = 34,
    Numpad2 = 35,
    Numpad3 = 36,
    Numpad4 = 37,
    Numpad5 = 38,
    Numpad6 = 39,
    Numpad7 = 40,
    Numpad8 = 41,
    Numpad9 = 42,
    Cancel = 43,
    Clear = 44,
    Menu = 45,
    Pause = 46,
    Kana = 47,
    Hangul = 48,
    Junja = 49,
    Final = 50,
    Hanja = 51,
    Kanji = 52,
    Convert = 53,
    Select = 54,
    Print = 55,
    Execute = 56,
    Snapshot = 57,
    Insert = 58,
    Help = 59,
    Sleep = 60,
    Separator = 61,
    Scroll = 62,
    NumLock = 63,
    RWin = 64,
    Apps = 65,
    Multiply = 66,
    Add = 67,
    Subtract = 68,
    Decimal = 69,
    Divide = 70,
    Equals = 71,
    NumpadEnter = 72,
    RShift = 73,
    RControl = 74,
    RAlt = 75,
    VolumeMute = 76,
    VolumeUp = 77,
    VolumeDown = 78,
    Power = 79,
    CtrlAltDel = 100,
    LockScreen = 101,
}
impl ControlKey {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::Alt => "Alt",
            Self::Backspace => "Backspace",
            Self::CapsLock => "CapsLock",
            Self::Control => "Control",
            Self::Delete => "Delete",
            Self::DownArrow => "DownArrow",
            Self::End => "End",
            Self::Escape => "Escape",
            Self::F1 => "F1",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::Home => "Home",
            Self::LeftArrow => "LeftArrow",
            Self::Meta => "Meta",
            Self::Option => "Option",
            Self::PageDown => "PageDown",
            Self::PageUp => "PageUp",
            Self::Return => "Return",
            Self::RightArrow => "RightArrow",
            Self::Shift => "Shift",
            Self::Space => "Space",
            Self::Tab => "Tab",
            Self::UpArrow => "UpArrow",
            Self::Numpad0 => "Numpad0",
            Self::Numpad1 => "Numpad1",
            Self::Numpad2 => "Numpad2",
            Self::Numpad3 => "Numpad3",
            Self::Numpad4 => "Numpad4",
            Self::Numpad5 => "Numpad5",
            Self::Numpad6 => "Numpad6",
            Self::Numpad7 => "Numpad7",
            Self::Numpad8 => "Numpad8",
            Self::Numpad9 => "Numpad9",
            Self::Cancel => "Cancel",
            Self::Clear => "Clear",
            Self::Menu => "Menu",
            Self::Pause => "Pause",
            Self::Kana => "Kana",
            Self::Hangul => "Hangul",
            Self::Junja => "Junja",
            Self::Final => "Final",
            Self::Hanja => "Hanja",
            Self::Kanji => "Kanji",
            Self::Convert => "Convert",
            Self::Select => "Select",
            Self::Print => "Print",
            Self::Execute => "Execute",
            Self::Snapshot => "Snapshot",
            Self::Insert => "Insert",
            Self::Help => "Help",
            Self::Sleep => "Sleep",
            Self::Separator => "Separator",
            Self::Scroll => "Scroll",
            Self::NumLock => "NumLock",
            Self::RWin => "RWin",
            Self::Apps => "Apps",
            Self::Multiply => "Multiply",
            Self::Add => "Add",
            Self::Subtract => "Subtract",
            Self::Decimal => "Decimal",
            Self::Divide => "Divide",
            Self::Equals => "Equals",
            Self::NumpadEnter => "NumpadEnter",
            Self::RShift => "RShift",
            Self::RControl => "RControl",
            Self::RAlt => "RAlt",
            Self::VolumeMute => "VolumeMute",
            Self::VolumeUp => "VolumeUp",
            Self::VolumeDown => "VolumeDown",
            Self::Power => "Power",
            Self::CtrlAltDel => "CtrlAltDel",
            Self::LockScreen => "LockScreen",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unknown" => Some(Self::Unknown),
            "Alt" => Some(Self::Alt),
            "Backspace" => Some(Self::Backspace),
            "CapsLock" => Some(Self::CapsLock),
            "Control" => Some(Self::Control),
            "Delete" => Some(Self::Delete),
            "DownArrow" => Some(Self::DownArrow),
            "End" => Some(Self::End),
            "Escape" => Some(Self::Escape),
            "F1" => Some(Self::F1),
            "F10" => Some(Self::F10),
            "F11" => Some(Self::F11),
            "F12" => Some(Self::F12),
            "F2" => Some(Self::F2),
            "F3" => Some(Self::F3),
            "F4" => Some(Self::F4),
            "F5" => Some(Self::F5),
            "F6" => Some(Self::F6),
            "F7" => Some(Self::F7),
            "F8" => Some(Self::F8),
            "F9" => Some(Self::F9),
            "Home" => Some(Self::Home),
            "LeftArrow" => Some(Self::LeftArrow),
            "Meta" => Some(Self::Meta),
            "Option" => Some(Self::Option),
            "PageDown" => Some(Self::PageDown),
            "PageUp" => Some(Self::PageUp),
            "Return" => Some(Self::Return),
            "RightArrow" => Some(Self::RightArrow),
            "Shift" => Some(Self::Shift),
            "Space" => Some(Self::Space),
            "Tab" => Some(Self::Tab),
            "UpArrow" => Some(Self::UpArrow),
            "Numpad0" => Some(Self::Numpad0),
            "Numpad1" => Some(Self::Numpad1),
            "Numpad2" => Some(Self::Numpad2),
            "Numpad3" => Some(Self::Numpad3),
            "Numpad4" => Some(Self::Numpad4),
            "Numpad5" => Some(Self::Numpad5),
            "Numpad6" => Some(Self::Numpad6),
            "Numpad7" => Some(Self::Numpad7),
            "Numpad8" => Some(Self::Numpad8),
            "Numpad9" => Some(Self::Numpad9),
            "Cancel" => Some(Self::Cancel),
            "Clear" => Some(Self::Clear),
            "Menu" => Some(Self::Menu),
            "Pause" => Some(Self::Pause),
            "Kana" => Some(Self::Kana),
            "Hangul" => Some(Self::Hangul),
            "Junja" => Some(Self::Junja),
            "Final" => Some(Self::Final),
            "Hanja" => Some(Self::Hanja),
            "Kanji" => Some(Self::Kanji),
            "Convert" => Some(Self::Convert),
            "Select" => Some(Self::Select),
            "Print" => Some(Self::Print),
            "Execute" => Some(Self::Execute),
            "Snapshot" => Some(Self::Snapshot),
            "Insert" => Some(Self::Insert),
            "Help" => Some(Self::Help),
            "Sleep" => Some(Self::Sleep),
            "Separator" => Some(Self::Separator),
            "Scroll" => Some(Self::Scroll),
            "NumLock" => Some(Self::NumLock),
            "RWin" => Some(Self::RWin),
            "Apps" => Some(Self::Apps),
            "Multiply" => Some(Self::Multiply),
            "Add" => Some(Self::Add),
            "Subtract" => Some(Self::Subtract),
            "Decimal" => Some(Self::Decimal),
            "Divide" => Some(Self::Divide),
            "Equals" => Some(Self::Equals),
            "NumpadEnter" => Some(Self::NumpadEnter),
            "RShift" => Some(Self::RShift),
            "RControl" => Some(Self::RControl),
            "RAlt" => Some(Self::RAlt),
            "VolumeMute" => Some(Self::VolumeMute),
            "VolumeUp" => Some(Self::VolumeUp),
            "VolumeDown" => Some(Self::VolumeDown),
            "Power" => Some(Self::Power),
            "CtrlAltDel" => Some(Self::CtrlAltDel),
            "LockScreen" => Some(Self::LockScreen),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClipboardFormat {
    Text = 0,
    Rtf = 1,
    Html = 2,
    ImageRgba = 21,
    ImagePng = 22,
    ImageSvg = 23,
    Special = 31,
}
impl ClipboardFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Text => "Text",
            Self::Rtf => "Rtf",
            Self::Html => "Html",
            Self::ImageRgba => "ImageRgba",
            Self::ImagePng => "ImagePng",
            Self::ImageSvg => "ImageSvg",
            Self::Special => "Special",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Text" => Some(Self::Text),
            "Rtf" => Some(Self::Rtf),
            "Html" => Some(Self::Html),
            "ImageRgba" => Some(Self::ImageRgba),
            "ImagePng" => Some(Self::ImagePng),
            "ImageSvg" => Some(Self::ImageSvg),
            "Special" => Some(Self::Special),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileType {
    Dir = 0,
    DirLink = 2,
    DirDrive = 3,
    File = 4,
    FileLink = 5,
}
impl FileType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Dir => "Dir",
            Self::DirLink => "DirLink",
            Self::DirDrive => "DirDrive",
            Self::File => "File",
            Self::FileLink => "FileLink",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Dir" => Some(Self::Dir),
            "DirLink" => Some(Self::DirLink),
            "DirDrive" => Some(Self::DirDrive),
            "File" => Some(Self::File),
            "FileLink" => Some(Self::FileLink),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ImageQuality {
    NotSet = 0,
    Low = 2,
    Balanced = 3,
    Best = 4,
}
impl ImageQuality {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotSet => "NotSet",
            Self::Low => "Low",
            Self::Balanced => "Balanced",
            Self::Best => "Best",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NotSet" => Some(Self::NotSet),
            "Low" => Some(Self::Low),
            "Balanced" => Some(Self::Balanced),
            "Best" => Some(Self::Best),
            _ => None,
        }
    }
}
